### ISSUE TITLE
build doc fails: make.py

### ISSUE THREAD

**Issue by atravert** [spectrochempy/spectrochempy#138]
**Describe the bug**
execution of make.py generates an error , and a build fail (travis ci). 

**To Reproduce**
python make.py -H

**Expected behavior**
should generate the html documentation

**Screenshots**
Traceback (most recent call last):

  File "docs/make.py", line 388, in <module>

    Build()

  File "docs/make.py", line 117, in __call__

    self.make_changelog(args.changelogs)

  File "docs/make.py", line 332, in make_changelog

    tag = json.loads(requests.get(LATEST).text)['tag_name'].split('.')

KeyError: 'tag_name'

The command "if [[ $TEST = true ]]; then echo "RUNNING TESTS"; coverage run -m pytest -v --flake8 -k "not test_example" --nodisplay; pytest -v --flake8 -k "test_example" --nodisplay; elif [[ $DEPLOY = true ]]; then echo "BUILDING AND UPLOADING ON ANACONDA"; bash .ci/scripts/conda-upload.sh;

elif [[ $BUILDOCS = true ]]; then echo "BUILDING DOCS" echo "cloning spectrochempy.github.io repository"; git clone --branch=gh-pages --single-branch https://github.com/spectrochempy/spectrochempy.git $HOME/spectrochempy_docs/html; apt-get install texlive-full; python docs/make.py --clean --sync --html --pdf; fi" exited with 1.

**Desktop (please complete the following information):**
-  automatic build by Travis ci
- same error under windows10

**Comment by atravert** [comment]
FIX #139 solved the issue.
