### ISSUE TITLE
pca reconstruction for an omnic dataset

### ISSUE THREAD

**Issue by fernandezc** [spectrochempy/spectrochempy#23]
Author: @fernandezc (Christian Fernandez )

Redmine Issue: 15, https://redmine.spectrochempy.fr/issues/15

---

code to generate the Error:

```
from spectrochempy import *

X = read_omnic('irdata/nh4y-activation.spg')
mypca = PCA(X)
xhat = mypca.reconstruct(n_pc=3)
```

provisional fix: replace `X += self._center`  by  `X += self._center.data`at line ~391 \(pca.py\)

Apparently due tu units/pint issue. debuggr output:

`Traceback (most recent call last):`  
`File "C:\Users\Arnaud\Dropbox\Programmes\spectrochempy\spectrochempy\core\dataset\ndarray.py", line 1476, in to`  
`q = Quantity(1., self._units).to(units)`  
`File "C:\Miniconda3\envs\scpy-dev\lib\site-packages\pint\quantity.py", line 375, in to`  
`magnitude = self._convert_magnitude_not_inplace(other, *contexts, **ctx_kwargs)`  
`File "C:\Miniconda3\envs\scpy-dev\lib\site-packages\pint\quantity.py", line 343, in _convert_magnitude_not_inplace`  
`return self._REGISTRY.convert(self._magnitude, self._units, other)`  
`File "C:\Miniconda3\envs\scpy-dev\lib\site-packages\pint\registry.py", line 711, in convert`  
`return self._convert(value, src, dst, inplace)`  
`File "C:\Miniconda3\envs\scpy-dev\lib\site-packages\pint\registry.py", line 1242, in _convert`  
`return super(ContextRegistry, self)._convert(value, src, dst, inplace)`  
`File "C:\Miniconda3\envs\scpy-dev\lib\site-packages\pint\registry.py", line 990, in _convert`  
`dst_offset_unit = self._validate_and_extract(dst)`  
`File "C:\Miniconda3\envs\scpy-dev\lib\site-packages\pint\registry.py", line 940, in _validate_and_extract`  
`nonmult_units = [(u, e) for u, e in units.items()`  
`AttributeError: 'NoneType' object has no attribute 'items'`  
`sys:1: ResourceWarning: unclosed <socket.socket fd=848, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 53915), raddr=('127.0.0.1', 53913)>`

‌

**Comment by fernandezc** [comment]
From: @fernandezc (Christian Fernandez )
Date: 2020-05-02T08:49:17Z

---

The error comes mainly because some functions like `diag`, `dot`, and `svd` do not handle units correctly. 

The result is that such a simple thing as:
``` python
X += self._center
```
fails  because X has lost units in previous operations (it is unitless) while self._center is still with the original units of the input NDDataset (absorbance). 

So I am in the process to correct these functions. 

But, in the present case, it would also be interesting to relax the condition on addition and subtraction, as unitless and dimensionless (absorbance) should behave as compatible unit. I think.
