### ISSUE TITLE
Error in Travis Build for a PR

### ISSUE THREAD

**Issue by atravert** [spectrochempy/spectrochempy#267]
**Describe the bug**
The following error occured while travis built for py 3.7, 3.8 and 3.9  (it passed for py 3.6). No change has been made to setup.py and to any configuration script since the last PR one month ago. Any idea ? 
  
```
$ python setup.py install;
/home/travis/miniconda/envs/scpy3.7/lib/python3.7/site-packages/setuptools_scm/git.py:88: UserWarning: "/home/travis/build/spectrochempy/spectrochempy" is shallow and may cause errors
  warnings.warn(f'"{wd.path}" is shallow and may cause errors')
/home/travis/miniconda/envs/scpy3.7/lib/python3.7/site-packages/setuptools_scm/git.py:88: UserWarning: "/home/travis/build/spectrochempy/spectrochempy" is shallow and may cause errors
  warnings.warn(f'"{wd.path}" is shallow and may cause errors')
running install
Stylesheets installed in /home/travis/.config/matplotlib/stylelib/notebook.mplstyle
Traceback (most recent call last):
  File "setup.py", line 142, in <module>
    setup(**setup_args)
  File "/home/travis/miniconda/envs/scpy3.7/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/home/travis/miniconda/envs/scpy3.7/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/travis/miniconda/envs/scpy3.7/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/travis/miniconda/envs/scpy3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 87, in run
    _install_mpl()
  File "setup.py", line 58, in _install_mpl
    _dir_data = Path(mpl.rcParams['datapath'])
  File "/home/travis/miniconda/envs/scpy3.7/lib/python3.7/site-packages/matplotlib/__init__.py", line 621, in __getitem__
    return dict.__getitem__(self, key)
KeyError: 'datapath'

The command "python setup.py install;" failed and exited with 1 during .
```

**Comment by fernandezc** [comment]
Hi Arnaud
I have seen this some time ago... as the error is a key error in RcParams (Matplotlib) I suspect that it is due to a recent new version of Matplotlib. I will have a look at this as soon as possible.

**Comment by atravert** [comment]
Thanks christian,
There is no emergency for this :-)

**Comment by atravert** [comment]
I have started to fix the issue, but now  an error is raised by traitlets (travis build with python 3.6 still OK). This is beyond my capabilities :-) 
  
==================================== ERRORS ====================================

_____________ ERROR collecting docs/userguide/plotting/plotting.py _____________

spectrochempy/plot_preferences.py:664: in _apply_style

    setattr(self, name_, value)

../../../miniconda/envs/scpy3.7/lib/python3.7/site-packages/traitlets/traitlets.py:604: in __set__

    self.set(obj, value)

../../../miniconda/envs/scpy3.7/lib/python3.7/site-packages/traitlets/traitlets.py:578: in set

    new_value = self._validate(obj, value)

../../../miniconda/envs/scpy3.7/lib/python3.7/site-packages/traitlets/traitlets.py:610: in _validate

    value = self.validate(obj, value)

../../../miniconda/envs/scpy3.7/lib/python3.7/site-packages/traitlets/traitlets.py:2295: in validate

    self.error(obj, value)

../../../miniconda/envs/scpy3.7/lib/python3.7/site-packages/traitlets/traitlets.py:690: in error

    raise TraitError(e)

E   traitlets.traitlets.TraitError: The 'lines_dash_capstyle' trait of a PlotPreferences instance expected any of ['butt', 'round', 'projecting'], not the str 'CapStyle.butt'.

During handling of the above exception, another exception occurred:

docs/userguide/plotting/plotting.py:277: in <module>

    prefs.makestyle()

spectrochempy/core/dataset/ndplot.py:249: in makestyle

    self.style = filename

spectrochempy/core/dataset/meta.py:106: in __setattr__

    self[key] = value

spectrochempy/core/dataset/ndplot.py:77: in __setitem__

    setattr(plot_preferences, key, value)

../../../miniconda/envs/scpy3.7/lib/python3.7/site-packages/traitlets/traitlets.py:604: in __set__

    self.set(obj, value)

../../../miniconda/envs/scpy3.7/lib/python3.7/site-packages/traitlets/traitlets.py:593: in set

    obj._notify_trait(self.name, old_value, new_value)

../../../miniconda/envs/scpy3.7/lib/python3.7/site-packages/traitlets/traitlets.py:1222: in _notify_trait

    type='change',

../../../miniconda/envs/scpy3.7/lib/python3.7/site-packages/traitlets/traitlets.py:1227: in notify_change

    return self._notify_observers(change)

../../../miniconda/envs/scpy3.7/lib/python3.7/site-packages/traitlets/traitlets.py:1264: in _notify_observers

    c(event)

spectrochempy/plot_preferences.py:609: in _style_changed

    raise e

spectrochempy/plot_preferences.py:607: in _style_changed

    self._apply_style(_style)

spectrochempy/plot_preferences.py:676: in _apply_style

    value = type(self.traits()[name_].default_value)(eval(value))

<string>:1: in <module>

    ???

E   NameError: name 'CapStyle' is not defined
