### ISSUE TITLE
[Bug]: IPython required

### ISSUE THREAD

**Issue by petsuter** [spectrochempy/spectrochempy#401]
### What happened?

```
>>> import spectrochempy as scp
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "spectrochempy\__init__.py", line 59, in <module>
    from spectrochempy import api
  File "spectrochempy\api.py", line 18, in <module>
    from IPython.core.interactiveshell import InteractiveShell
```

### What did you expect to happen?

No error when IPython is not installed. Or a dependency on IPython should be added so it gets installed automatically, if it's required for spectrochempy to work.

### Environment

I can't import scp.

**Comment by fernandezc** [comment]
Thank you for the issue reporting. 
Can you tell me how you installed spectrochempy? If you use Conda in principle all this dependencies should be installed.

**Comment by fernandezc** [comment]
If you used pip, did you follows the instructions here? https://www.spectrochempy.fr/stable/gettingstarted/install/install_mac.html#installation-using-pip
especially the installation of the requirements?

**Comment by petsuter** [comment]
Thank you.

I simply used `pip install spectrochempy`.

I did not see the install instructions. Usually `pip install <library-name>` installs everything that is required. (And it did install various dependencies, but apparently not all of them.)

I then used ` pip install ipython` to get past this error, but just wanted to let you know.

**Comment by fernandezc** [comment]
Ok Thanks. I must admit we did not work a lot on the setup for pip installation (the initial development was done only using conda, and the pypi package is quite new). Probably as you said every thing may be installed automatically. 
Meanwhile, if you want to have a look at spectrochempy, execute this:

```
$ python -m pip install -r https://www.spectrochempy.fr/downloads/requirements.txt
```

**Comment by petsuter** [comment]
Thanks.

I'm no expert on all of that either; I think according to [these docs](https://packaging.python.org/en/latest/discussions/install-requires-vs-requirements/) that the `install_requires` section in [setup.py](https://github.com/spectrochempy/spectrochempy/blob/958eb85e4f4a9129decb4d63169708d581247477/setup.py#L144) should list all the things currently listed in `requirements.txt`.

I tried your suggestion:
```
py -m pip install -r https://www.spectrochempy.fr/downloads/requirements.txt
Collecting git+https://github.com/jjhelmus/nmrglue.git (from -r https://www.spectrochempy.fr/downloads/requirements.txt (line 7))
  Cloning https://github.com/jjhelmus/nmrglue.git to c:\users\peter\appdata\local\temp\pip-req-build-mph76cxt
  ERROR: Error [WinError 2] The system cannot find the file specified while executing command git clone -q https://github.com/jjhelmus/nmrglue.git 'C:\Users\peter\AppData\Local\Temp\pip-req-build-mph76cxt'
ERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH?
```

I added git, and tried again. I still got some errors:
```
...
ERROR: After October 2020 you may experience errors when installing or updating packages. This is because pip will change the way that it resolves dependency conflicts.

We recommend you use --use-feature=2020-resolver to test your packages with the new resolver before it becomes the default.

numba 0.55.1 requires numpy<1.22,>=1.18, but you'll have numpy 1.22.2 which is incompatible.
...
```
But `import spectrochempy` now seems to work despite that.
