### ISSUE TITLE
Deprecation warning with numpy elementwise == comparison 

### ISSUE THREAD

**Issue by fernandezc** [spectrochempy/spectrochempy#48]
Author: @fernandezc (Christian Fernandez )

Redmine Issue: 44, https://redmine.spectrochempy.fr/issues/44

---

Turning DeprecationWarnings to Error for test result in one problem to solve (Numpy deprecation warning)

``` python
FAILED [ 95%]testing ../docs/user/userguide/dataset/2_ndpanel.py
env base
1 SpectroChemPy's API - v.0.1.17-dev.82
© Copyright 2014-2020 - A.Travert & C.Fernandez @ LCS
 None
Loading SpectroChemPy API: 100%|██████████| 1211/1211 [00:05<00:00, 242.11it/s]
ValueError: operands could not be broadcast together with shapes (10,) (6,) 

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "../docs/user/userguide/dataset/2_ndpanel.py", line 75, in <module>
    ndp = NDPanel(nda, ndb)
  File "/Users/christian/Dropbox/SCP/spectrochempy/spectrochempy/core/dataset/ndpanel.py", line 126, in __init__
    self._set_datasets(datasets, merge=merge, align=align)
  File "/Users/christian/Dropbox/SCP/spectrochempy/spectrochempy/core/dataset/ndpanel.py", line 344, in _set_datasets
    self.add_dataset(dataset, merge=merge, align=align)
  File "/Users/christian/Dropbox/SCP/spectrochempy/spectrochempy/core/dataset/ndpanel.py", line 465, in add_dataset
    if merge and self._do_merge_or_align(self._dataset_to_be_added, dim, merge, align):
  File "/Users/christian/Dropbox/SCP/spectrochempy/spectrochempy/core/dataset/ndpanel.py", line 401, in _do_merge_or_align
    can_merge, can_align = self._equal_dim_properties(prop, curprop)
  File "/Users/christian/Dropbox/SCP/spectrochempy/spectrochempy/core/dataset/ndpanel.py", line 375, in _equal_dim_properties
    return can_merge_or_align(this['coord'], other['coord'])
  File "/Users/christian/Dropbox/SCP/spectrochempy/spectrochempy/core/processors/align.py", line 51, in can_merge_or_align
    if (coord1 == coord2):
  File "/Users/christian/Dropbox/SCP/spectrochempy/spectrochempy/core/dataset/ndarray.py", line 281, in __eq__
    eq &= np.all(sattr == oattr)
DeprecationWarning: elementwise == comparison failed; this will raise an error in the future.

test_utils/test_py_in_docs.py:18 (test_example[../docs/user/userguide/dataset/2_ndpanel.py])
test_utils/test_py_in_docs.py:42: in test_example
    assert not e, message.decode('utf8')
E   AssertionError: SpectroChemPy's API - v.0.1.17-dev.82
E     © Copyright 2014-2020 - A.Travert & C.Fernandez @ LCS
E     
E   assert not 1

```

**Comment by fernandezc** [comment]
From: @fernandezc (Christian Fernandez )
Date: 2020-05-27T21:22:22Z

---

duplicate of #73
