### ISSUE TITLE
[Bug]: pre-commit error

### ISSUE THREAD

**Issue by atravert** [spectrochempy/spectrochempy#568]
### What happened?

Hi Christian,

I have the following error when making a commit, which is similar as this one: https://stackoverflow.com/questions/75269700/pre-commit-fails-to-install-isort-5-11-4-with-error-runtimeerror-the-poetry-co

It seems that the version of isort (in /.pre-commit-config.yaml ?) should be set to 5.12.0

Here the pre-commit.log file:

### version information

```
pre-commit version: 3.0.3
git --version: git version 2.38.1.windows.1
sys.version:
    3.10.9 | packaged by conda-forge | (main, Feb  2 2023, 20:14:58) [MSC v.1929 64 bit (AMD64)]
sys.executable: C:\miniconda3\envs\scpy-dev\python.exe
os.name: nt
sys.platform: win32
```

### error information

```
An unexpected error has occurred: CalledProcessError: command: ('C:\\Users\\traverta\\.cache\\pre-commit\\reponpuwm6py\\py_env-python3\\Scripts\\python.EXE', '-mpip', 'install', '.')
return code: 1
stdout:
    Processing c:\users\traverta\.cache\pre-commit\reponpuwm6py
      Installing build dependencies: started
      Installing build dependencies: finished with status 'done'
      Getting requirements to build wheel: started
      Getting requirements to build wheel: finished with status 'done'
      Preparing metadata (pyproject.toml): started
      Preparing metadata (pyproject.toml): finished with status 'error'
    
stderr:
      error: subprocess-exited-with-error
      
      Preparing metadata (pyproject.toml) did not run successfully.
      exit code: 1
      
      [14 lines of output]
      Traceback (most recent call last):
        File "C:\Users\traverta\.cache\pre-commit\reponpuwm6py\py_env-python3\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 351, in <module>
          main()
        File "C:\Users\traverta\.cache\pre-commit\reponpuwm6py\py_env-python3\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 333, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\traverta\.cache\pre-commit\reponpuwm6py\py_env-python3\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 152, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "C:\Users\traverta\AppData\Local\Temp\pip-build-env-z_oye1e5\overlay\Lib\site-packages\poetry\core\masonry\api.py", line 40, in prepare_metadata_for_build_wheel
          poetry = Factory().create_poetry(Path(".").resolve(), with_groups=False)
        File "C:\Users\traverta\AppData\Local\Temp\pip-build-env-z_oye1e5\overlay\Lib\site-packages\poetry\core\factory.py", line 57, in create_poetry
          raise RuntimeError("The Poetry configuration is invalid:\n" + message)
      RuntimeError: The Poetry configuration is invalid:
        - [extras.pipfile_deprecated_finder.2] 'pip-shims<=0.3.4' does not match '^[a-zA-Z-_.0-9]+$'
      
      [end of output]
      
      note: This error originates from a subprocess, and is likely not a problem with pip.
    error: metadata-generation-failed
    
    Encountered error while generating package metadata.
    
    See above for output.
    
    note: This is an issue with the package mentioned above, not pip.
    hint: See above for details.
    
```

```
Traceback (most recent call last):
  File "C:\miniconda3\envs\scpy-dev\lib\site-packages\pre_commit\error_handler.py", line 73, in error_handler
    yield
  File "C:\miniconda3\envs\scpy-dev\lib\site-packages\pre_commit\main.py", line 366, in main
    return hook_impl(
  File "C:\miniconda3\envs\scpy-dev\lib\site-packages\pre_commit\commands\hook_impl.py", line 254, in hook_impl
    return retv | run(config, store, ns)
  File "C:\miniconda3\envs\scpy-dev\lib\site-packages\pre_commit\commands\run.py", line 437, in run
    install_hook_envs(to_install, store)
  File "C:\miniconda3\envs\scpy-dev\lib\site-packages\pre_commit\repository.py", line 239, in install_hook_envs
    _hook_install(hook)
  File "C:\miniconda3\envs\scpy-dev\lib\site-packages\pre_commit\repository.py", line 86, in _hook_install
    lang.install_environment(
  File "C:\miniconda3\envs\scpy-dev\lib\site-packages\pre_commit\languages\python.py", line 214, in install_environment
    helpers.run_setup_cmd(prefix, install_cmd)
  File "C:\miniconda3\envs\scpy-dev\lib\site-packages\pre_commit\languages\helpers.py", line 49, in run_setup_cmd
    cmd_output_b(*cmd, cwd=prefix.prefix_dir, **kwargs)
  File "C:\miniconda3\envs\scpy-dev\lib\site-packages\pre_commit\util.py", line 115, in cmd_output_b
    raise CalledProcessError(returncode, cmd, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('C:\\Users\\traverta\\.cache\\pre-commit\\reponpuwm6py\\py_env-python3\\Scripts\\python.EXE', '-mpip', 'install', '.')
return code: 1
stdout:
    Processing c:\users\traverta\.cache\pre-commit\reponpuwm6py
      Installing build dependencies: started
      Installing build dependencies: finished with status 'done'
      Getting requirements to build wheel: started
      Getting requirements to build wheel: finished with status 'done'
      Preparing metadata (pyproject.toml): started
      Preparing metadata (pyproject.toml): finished with status 'error'
    
stderr:
      error: subprocess-exited-with-error
      
      Preparing metadata (pyproject.toml) did not run successfully.
      exit code: 1
      
      [14 lines of output]
      Traceback (most recent call last):
        File "C:\Users\traverta\.cache\pre-commit\reponpuwm6py\py_env-python3\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 351, in <module>
          main()
        File "C:\Users\traverta\.cache\pre-commit\reponpuwm6py\py_env-python3\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 333, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\traverta\.cache\pre-commit\reponpuwm6py\py_env-python3\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 152, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "C:\Users\traverta\AppData\Local\Temp\pip-build-env-z_oye1e5\overlay\Lib\site-packages\poetry\core\masonry\api.py", line 40, in prepare_metadata_for_build_wheel
          poetry = Factory().create_poetry(Path(".").resolve(), with_groups=False)
        File "C:\Users\traverta\AppData\Local\Temp\pip-build-env-z_oye1e5\overlay\Lib\site-packages\poetry\core\factory.py", line 57, in create_poetry
          raise RuntimeError("The Poetry configuration is invalid:\n" + message)
      RuntimeError: The Poetry configuration is invalid:
        - [extras.pipfile_deprecated_finder.2] 'pip-shims<=0.3.4' does not match '^[a-zA-Z-_.0-9]+$'
      
      [end of output]
      
      note: This error originates from a subprocess, and is likely not a problem with pip.
    error: metadata-generation-failed
    
    Encountered error while generating package metadata.
    
    See above for output.
    
    note: This is an issue with the package mentioned above, not pip.
    hint: See above for details.
```

### Environment

INSTALLED VERSIONS
------------------
commit: None
python: 3.10.9 | packaged by conda-forge | (main, Feb  2 2023, 20:14:58) [MSC v.1929 64 bit (AMD64)]
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 142 Stepping 12, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: ('en_US', 'ISO8859-1')

quadprog: 0.1.11
brukeropusreader: 1.3
numpy-quaternion: None
cffconvert: 2.0.0
colorama: 0.4.6
dill: 0.3.6
ipython: None
jinja2: 3.1.2
matplotlib: 3.6.2
numba: 0.56.4
numpy: 1.23.5
numpydoc: 1.5.0
pint: 0.20.1
pytz: 2022.7.1
requests: 2.28.1
scipy: 1.9.3
tqdm: 4.64.1
traitlets: 5.8.0
traittypes: 0.2.1
xlrd: 2.0.1
pyyaml: None
ipywidgets: 8.0.4
widgetsnbextension: 4.0.5
jupyterlab_widgets: 3.0.5
ipympl: 0.9.2
setuptools: 65.6.3
setuptools_scm: 7.1.0
gitpython: None
jupyterlab: 3.5.2
nodejs: 0.1.1
pytest: None
pytest-doctestplus: None
pytest-flake8: None
pytest-mock: None
pyfakefs: None
pep8-naming: None
scikit-image: None
coverage: None
black: None
pre-commit: None
mamba: None
docrep: None
jupytext: None
sphinx==5.3: None
sphinx_rtd_theme==1.1: None
autodocsumm: None
sphinx-gallery: None
nbsphinx: None
jupyter_sphinx: None
json5: 0.9.5
sphinx-copybutton: None
pandoc: None
autodoc_traits: None

**Comment by fernandezc** [comment]
Hi Arnaud, 
I do not such problem. Have you try to change the version in `.pre-commit-config.yaml` (line36)

**Comment by atravert** [comment]
Yesn I just tried (my branch: feature/mcr_als) and it seems to work.

**Comment by fernandezc** [comment]
OK It works also for me, lets update the configuration I do the PR immediately!
