### ISSUE TITLE
Windows test workflow always ends with an error (non-critical)

### ISSUE THREAD

**Issue by fernandezc** [spectrochempy/spectrochempy#677]
### What happened?

Whenever a test action completes with the Windows operating system, an exception message appears (which is not the case with other operating systems) - see below log output and e.g. https://github.com/spectrochempy/spectrochempy/actions/runs/5201282168/jobs/9381210957. This is not critical, as it doesn't cause the action to fail. But it would be nice to remove it. 

@atravert Do you have any idea why this is happening?

### What did you expect to happen?

Clean ending!

### Relevant log output

```python
12.73s call     tests/test_core/test_plotters/test_plot2D.py::test_plot2D
[112](https://github.com/spectrochempy/spectrochempy/actions/runs/5201282168/jobs/9381210957#step:7:113)
12.69s call     tests/test_docs/test_py_in_docs.py::test_nbsphinx_script_[script3]
[113](https://github.com/spectrochempy/spectrochempy/actions/runs/5201282168/jobs/9381210957#step:7:114)
================= 499 passed, 22 skipped in 675.95s (0:11:15) =================
[114](https://github.com/spectrochempy/spectrochempy/actions/runs/5201282168/jobs/9381210957#step:7:115)
Exception ignored in atexit callback: <bound method InteractiveShell.atexit_operations of <IPython.terminal.interactiveshell.TerminalInteractiveShell object at 0x0000029A8F76EC80>>
[115](https://github.com/spectrochempy/spectrochempy/actions/runs/5201282168/jobs/9381210957?pr=676#step:7:116)
Traceback (most recent call last):
[116](https://github.com/spectrochempy/spectrochempy/actions/runs/5201282168/jobs/9381210957?pr=676#step:7:117)
  File "C:\Users\runneradmin\.virtualenvs\.venv\lib\site-packages\IPython\core\interactiveshell.py", line 3880, in atexit_operations
[117](https://github.com/spectrochempy/spectrochempy/actions/runs/5201282168/jobs/9381210957?pr=676#step:7:118)
    tfile.unlink()
[118](https://github.com/spectrochempy/spectrochempy/actions/runs/5201282168/jobs/9381210957?pr=676#step:7:119)
  File "C:\hostedtoolcache\windows\Python\3.10.11\x64\lib\pathlib.py", line 1206, in unlink
[119](https://github.com/spectrochempy/spectrochempy/actions/runs/5201282168/jobs/9381210957?pr=676#step:7:120)
    self._accessor.unlink(self)
[120](https://github.com/spectrochempy/spectrochempy/actions/runs/5201282168/jobs/9381210957?pr=676#step:7:121)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\tmpjieug3b3test_hist.sqlite'
[121](https://github.com/spectrochempy/spectrochempy/actions/runs/5201282168/jobs/9381210957?pr=676#step:7:122)
sys:1: ResourceWarning: unclosed file <_io.TextIOWrapper name=54 encoding='utf8'>
[122](https://github.com/spectrochempy/spectrochempy/actions/runs/5201282168/jobs/9381210957?pr=676#step:7:123)
sys:1: ResourceWarning: unclosed file <_io.TextIOWrapper name=53 encoding='utf8'>
[123](https://github.com/spectrochempy/spectrochempy/actions/runs/5201282168/jobs/9381210957?pr=676#step:7:124)
sys:1: ResourceWarning: unclosed file <_io.TextIOWrapper name=52 encoding='utf8'>
[124](https://github.com/spectrochempy/spectrochempy/actions/runs/5201282168/jobs/9381210957?pr=676#step:7:125)
sys:1: ResourceWarning: unclosed file <_io.TextIOWrapper name=51 encoding='utf8'>
[125](https://github.com/spectrochempy/spectrochempy/actions/runs/5201282168/jobs/9381210957?pr=676#step:7:126)
sys:1: ResourceWarning: unclosed file <_io.TextIOWrapper name=50 encoding='utf8'>
[126](https://github.com/spectrochempy/spectrochempy/actions/runs/5201282168/jobs/9381210957?pr=676#step:7:127)
sys:1: ResourceWarning: unclosed file <_io.TextIOWrapper name=49 encoding='utf8'>
[127](https://github.com/spectrochempy/spectrochempy/actions/runs/5201282168/jobs/9381210957?pr=676#step:7:128)
sys:1: ResourceWarning: unclosed file <_io.TextIOWrapper name=48 encoding='utf8'>
[128](https://github.com/spectrochempy/spectrochempy/actions/runs/5201282168/jobs/9381210957?pr=676#step:7:129)
sys:1: ResourceWarning: unclosed file <_io.TextIOWrapper name=47 encoding='utf8'>
[129](https://github.com/spectrochempy/spectrochempy/actions/runs/5201282168/jobs/9381210957?pr=676#step:7:130)
sys:1: ResourceWarning: unclosed file <_io.TextIOWrapper name=46 encoding='utf8'>
[130](https://github.com/spectrochempy/spectrochempy/actions/runs/5201282168/jobs/9381210957?pr=676#step:7:131)
sys:1: ResourceWarning: unclosed file <_io.TextIOWrapper name=45 encoding='utf8'>
[131](https://github.com/spectrochempy/spectrochempy/actions/runs/5201282168/jobs/9381210957?pr=676#step:7:132)
sys:1: ResourceWarning: unclosed file <_io.TextIOWrapper name=44 encoding='utf8'>
[132](https://github.com/spectrochempy/spectrochempy/actions/runs/5201282168/jobs/9381210957?pr=676#step:7:133)
sys:1: ResourceWarning: unclosed file <_io.TextIOWrapper name=43 encoding='utf8'>
[133](https://github.com/spectrochempy/spectrochempy/actions/runs/5201282168/jobs/9381210957?pr=676#step:7:134)
sys:1: ResourceWarning: unclosed file <_io.TextIOWrapper name=42 encoding='utf8'>
[134](https://github.com/spectrochempy/spectrochempy/actions/runs/5201282168/jobs/9381210957?pr=676#step:7:135)
sys:1: ResourceWarning: unclosed file <_io.TextIOWrapper name=41 encoding='utf8'>
[135](https://github.com/spectrochempy/spectrochempy/actions/runs/5201282168/jobs/9381210957?pr=676#step:7:136)
sys:1: ResourceWarning: unclosed file <_io.TextIOWrapper name=40 encoding='utf8'>
[136](https://github.com/spectrochempy/spectrochempy/actions/runs/5201282168/jobs/9381210957?pr=676#step:7:137)
sys:1: ResourceWarning: unclosed file <_io.TextIOWrapper name=39 encoding='utf8'>
[137](https://github.com/spectrochempy/spectrochempy/actions/runs/5201282168/jobs/9381210957?pr=676#step:7:138)
sys:1: ResourceWarning: unclosed file <_io.TextIOWrapper name=38 encoding='utf8'>
[138](https://github.com/spectrochempy/spectrochempy/actions/runs/5201282168/jobs/9381210957?pr=676#step:7:139)
sys:1: ResourceWarning: unclosed file <_io.TextIOWrapper name=37 encoding='utf8'>
[139](https://github.com/spectrochempy/spectrochempy/actions/runs/5201282168/jobs/9381210957?pr=676#step:7:140)
sys:1: ResourceWarning: unclosed file <_io.TextIOWrapper name=36 encoding='utf8'>
[140](https://github.com/spectrochempy/spectrochempy/actions/runs/5201282168/jobs/9381210957?pr=676#step:7:141)
sys:1: ResourceWarning: unclosed file <_io.TextIOWrapper name=35 encoding='utf8'>
[141](https://github.com/spectrochempy/spectrochempy/actions/runs/5201282168/jobs/9381210957?pr=676#step:7:142)
sys:1: ResourceWarning: unclosed file <_io.TextIOWrapper name=34 encoding='utf8'>
[142](https://github.com/spectrochempy/spectrochempy/actions/runs/5201282168/jobs/9381210957?pr=676#step:7:143)
sys:1: ResourceWarning: unclosed file <_io.TextIOWrapper name=33 encoding='utf8'>
[143](https://github.com/spectrochempy/spectrochempy/actions/runs/5201282168/jobs/9381210957?pr=676#step:7:144)
sys:1: ResourceWarning: unclosed file <_io.TextIOWrapper name=32 encoding='utf8'>
[144](https://github.com/spectrochempy/spectrochempy/actions/runs/5201282168/jobs/9381210957?pr=676#step:7:145)
sys:1: ResourceWarning: unclosed file <_io.TextIOWrapper name=31 encoding='utf8'>
[145](https://github.com/spectrochempy/spectrochempy/actions/runs/5201282168/jobs/9381210957?pr=676#step:7:146)
sys:1: ResourceWarning: unclosed file <_io.TextIOWrapper name=30 encoding='utf8'>
Coverage report to xml
```

### Environment

Github workflow

**Comment by fernandezc** [comment]
There is now less errors.

but this remains:

```
============================ slowest 10 durations =============================
10.23s call     tests/test_core/test_readers/test_read_labspec.py::test_read_labspec
9.53s call     tests/test_widgets/test_baselinecorrector.py::test_baselinecorrector_slicing
9.08s call     tests/test_core/test_readers/test_read.py::test_read
9.04s call     tests/test_core/test_readers/test_read_zip.py::test_read_zip
7.22s call     tests/test_analysis/test_baseline/test_baseline.py::test_baseline
6.07s call     tests/test_core/test_readers/test_read_topspin.py::test_readtopspin
5.73s call     tests/test_core/test_readers/test_read_wire.py::test_read_wire
5.35s call     tests/test_analysis/test_kinetic/test_kineticutilities.py::test_ABC
5.29s call     tests/test_core/test_plotters/test_plot2D.py::test_plot2D
4.92s call     tests/test_analysis/test_baseline/test_baseline_deprecated.py::test_userguide_example
================= 451 passed, 95 skipped in 153.30s (0:02:33) =================
Exception ignored in atexit callback <bound method InteractiveShell.atexit_operations of <IPython.terminal.interactiveshell.TerminalInteractiveShell object at 0x000002DC8B75BA10>>:
Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.13.1\x64\Lib\site-packages\IPython\core\interactiveshell.py", line 3957, in atexit_operations
    tfile.unlink()
  File "C:\hostedtoolcache\windows\Python\3.13.1\x64\Lib\pathlib\_local.py", line 746, in unlink
    os.unlink(self)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\tmpjcr0yctptest_hist.sqlite'
```
I'll try to solve it.

**Comment by fernandezc** [comment]
did not find a working solution .I'm closing this for now. It's really not critical.
